# config.yaml
model:
  name: "random_forest"
  type: "RandomForestClassifier"
  hyperparameters:
    n_estimators: 100
    max_depth: 10

data:
  path: "data/dataset.csv"
  test_size: 0.2
  random_state: 42

training:
  epochs: 10
  batch_size: 32
